# Generated by Django 3.2.7 on 2021-10-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entradamigrante',
            fields=[
                ('idmovilidad', models.AutoField(db_column='IdMovilidad', primary_key=True, serialize=False)),
                ('fechaentrada', models.DateTimeField(db_column='FechaEntrada', verbose_name='Fecha de Entrada')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=254, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Entrada Migrante',
                'verbose_name_plural': 'Entrada Migrantes',
                'db_table': 'entradamigrante',
                'managed': False,
            },
        ),
    ]
