# Generated by Django 3.2.7 on 2021-10-15 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('idvoluntario', models.AutoField(db_column='IdVoluntario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(db_column='Apellido', max_length=50, verbose_name='Apellido')),
                ('telefono', models.CharField(db_column='Telefono', max_length=16, verbose_name='Teléfono')),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('O', 'OTRO')], db_column='Genero', max_length=1, verbose_name='Género')),
                ('fechanacimiento', models.DateField(db_column='FechaNacimiento', verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(db_column='Nacionalidad', max_length=50, verbose_name='Nacionalidad')),
                ('correo', models.CharField(blank=True, help_text='Ingresa tu correo ejemplo: correo@dominio.com', max_length=75, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(db_column='Direccion', max_length=120, verbose_name='Dirección')),
                ('tipovoluntario', models.CharField(choices=[('L', 'LOCAL'), ('N', 'NACIONAL'), ('I', 'INTERNACIONAL')], db_column='TipoVoluntario', max_length=1, verbose_name='Tipo de Voluntario')),
                ('creencias', models.ForeignKey(db_column='FKCreenciasReligiosas', on_delete=django.db.models.deletion.DO_NOTHING, to='creencias.creencias')),
                ('usuario', models.ForeignKey(db_column='FKIdUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
