# Generated by Django 3.2.7 on 2021-10-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Migrante',
            fields=[
                ('idmigrante', models.AutoField(db_column='IdMigrante', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50, verbose_name='Nombre:')),
                ('apellido', models.CharField(db_column='Apellido', max_length=50, verbose_name='Apellido:')),
                ('telefono', models.CharField(db_column='Telefono', max_length=16, verbose_name='Teléfono:')),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('O', 'OTRO')], db_column='Genero', max_length=1, verbose_name='Género:')),
                ('edad', models.IntegerField(db_column='Edad', verbose_name='Edad:')),
                ('fechanacimiento', models.DateField(db_column='FechaNacimiento', verbose_name='Fecha de Nacimiento:')),
                ('nacionalidad', models.CharField(db_column='Nacionalidad', max_length=50, verbose_name='Nacionalidad:')),
            ],
            options={
                'verbose_name': 'Migrante',
                'verbose_name_plural': 'Migrantes',
                'db_table': 'migrante',
                'managed': False,
            },
        ),
    ]
