# Generated by Django 3.2.7 on 2021-10-08 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caravanamigrante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Migrante',
            fields=[
                ('idmigrante', models.AutoField(db_column='IdMigrante', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50, verbose_name='Nombre:')),
                ('apellido', models.CharField(db_column='Apellido', max_length=50, verbose_name='Apellido:')),
                ('telefono', models.CharField(db_column='Telefono', max_length=16, verbose_name='Teléfono:')),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('O', 'OTRO')], db_column='Genero', max_length=1, verbose_name='Género:')),
                ('edad', models.IntegerField(db_column='Edad', verbose_name='Edad:')),
                ('fechanacimiento', models.DateField(db_column='FechaNacimiento', verbose_name='Fecha de Nacimiento:')),
                ('nacionalidad', models.CharField(db_column='Nacionalidad', max_length=50, verbose_name='Nacionalidad:')),
                ('caravana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caravanamigrante.caravanamigrante')),
                ('usuario', models.ForeignKey(db_column='FKIdUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Migrante',
                'verbose_name_plural': 'Migrantes',
            },
        ),
    ]
