# Generated by Django 3.2.7 on 2021-10-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('idmodulo', models.AutoField(db_column='IdModulo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50, verbose_name='Módulo')),
                ('capacidad', models.IntegerField(db_column='Capacidad', verbose_name='Capacidad')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'modulo',
                'managed': False,
            },
        ),
    ]
