# Generated by Django 3.2.7 on 2021-10-08 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ruta', '0001_initial'),
        ('migrante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salidamigrante',
            fields=[
                ('idsalida', models.AutoField(db_column='IdSalida', primary_key=True, serialize=False)),
                ('fechasalida', models.DateTimeField(db_column='FechaSalida', verbose_name='Fecha de Salida')),
                ('migrante', models.ForeignKey(db_column='FKIdMigrante', on_delete=django.db.models.deletion.DO_NOTHING, to='migrante.migrante')),
                ('ruta', models.ForeignKey(db_column='FkIdRuta', on_delete=django.db.models.deletion.DO_NOTHING, to='ruta.ruta')),
            ],
            options={
                'verbose_name': 'Salida de Migrante',
                'verbose_name_plural': 'Salidas de Migrante',
            },
        ),
    ]
