# Generated by Django 3.2.7 on 2021-10-08 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voluntario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idasistencia', models.AutoField(primary_key=True, serialize=False)),
                ('entrada', models.TimeField(verbose_name='Entrada')),
                ('salida', models.TimeField(verbose_name='Salida')),
                ('creado', models.DateTimeField()),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voluntario.voluntario')),
            ],
        ),
    ]
