# Generated by Django 3.2.7 on 2021-10-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diasdevoluntariado',
            fields=[
                ('iddia', models.AutoField(db_column='IdDia', primary_key=True, serialize=False)),
                ('diaarealizar', models.CharField(choices=[('LUN', 'LUNES'), ('MAR', 'MARTES'), ('MIE', 'MIERCOLES'), ('JUE', 'JUEVES'), ('VIE', 'VIERNES'), ('SAB', 'SABADO'), ('DOM', 'DOMINGO')], db_column='DiaARealizar', max_length=3, verbose_name='Día a Realizar')),
                ('horasaprox', models.CharField(db_column='HorasAprox', max_length=10, verbose_name='Horas aprox')),
            ],
            options={
                'verbose_name': 'Día de Voluntariado',
                'verbose_name_plural': 'Días de Voluntariado',
                'db_table': 'diasdevoluntariado',
                'managed': False,
            },
        ),
    ]
