# Generated by Django 3.2.7 on 2021-10-08 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voluntario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diasdevoluntariado',
            fields=[
                ('iddia', models.AutoField(db_column='IdDia', primary_key=True, serialize=False)),
                ('diaarealizar', models.CharField(choices=[('LUN', 'LUNES'), ('MAR', 'MARTES'), ('MIE', 'MIERCOLES'), ('JUE', 'JUEVES'), ('VIE', 'VIERNES'), ('SAB', 'SABADO'), ('DOM', 'DOMINGO')], db_column='DiaARealizar', max_length=3, verbose_name='Día a Realizar')),
                ('horasaprox', models.CharField(db_column='HorasAprox', max_length=10, verbose_name='Horas aprox')),
                ('voluntario', models.ForeignKey(db_column='FKIdVoluntario', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dias_voluntario', to='voluntario.voluntario')),
            ],
            options={
                'verbose_name': 'Día de Voluntariado',
                'verbose_name_plural': 'Días de Voluntariado',
            },
        ),
    ]
