# Generated by Django 3.2.7 on 2021-10-08 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('origencaravana', '__first__'),
        ('pais', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caravanamigrante',
            fields=[
                ('idcaravana', models.AutoField(db_column='IdCaravana', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50, verbose_name='Nombre de Caravana')),
                ('origen', models.ForeignKey(db_column='FkOrigen', on_delete=django.db.models.deletion.DO_NOTHING, to='origencaravana.origencaravana')),
                ('país', models.ForeignKey(db_column='FkIdPais', on_delete=django.db.models.deletion.DO_NOTHING, to='pais.pais')),
            ],
            options={
                'verbose_name': 'Caravana Migrante',
                'verbose_name_plural': 'Caravana Migrantes',
            },
        ),
    ]
