# Generated by Django 3.2.7 on 2021-10-07 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipodonacion',
            fields=[
                ('idtipodonacion', models.AutoField(db_column='IdTipoDonacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=75, verbose_name='Tipo')),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('donacion', models.ForeignKey(db_column='FkIdDonacion', on_delete=django.db.models.deletion.DO_NOTHING, to='donacion.donacion')),
            ],
            options={
                'verbose_name': 'Tipo de Donación',
                'verbose_name_plural': 'Tipo de Donaciones',
            },
        ),
    ]
