# Generated by Django 3.2.7 on 2021-10-15 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidad', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('iddonacion', models.AutoField(db_column='IdDonacion', primary_key=True, serialize=False)),
                ('telefono', models.CharField(db_column='Telefono', max_length=18, verbose_name='Teléfono')),
                ('direccion', models.CharField(db_column='Direccion', max_length=254, verbose_name='Dirección')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=254, null=True, verbose_name='Descripción')),
                ('fechadeentrega', models.DateTimeField(db_column='FechaDeEntrega', verbose_name='Entrega')),
                ('nombre', models.ForeignKey(db_column='FKIdEntidad', on_delete=django.db.models.deletion.DO_NOTHING, to='entidad.entidad')),
                ('usuario', models.ForeignKey(db_column='FKIdUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
            },
        ),
    ]
