# Generated by Django 3.2.7 on 2021-10-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('iddonacion', models.AutoField(db_column='IdDonacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=200, verbose_name='Nombre o Entidad')),
                ('telefono', models.CharField(db_column='Telefono', max_length=18, verbose_name='Teléfono')),
                ('direccion', models.CharField(db_column='Direccion', max_length=254, verbose_name='Dirección')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=254, null=True, verbose_name='Descripción')),
                ('fechadeentrega', models.DateTimeField(db_column='FechaDeEntrega', verbose_name='Entrega')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'db_table': 'donacion',
                'managed': False,
            },
        ),
    ]
